version: '3'

services:
  postgres:
    container_name: fwd-postgres
    restart: always
    image: postgres:latest
    env_file:
      - database.env
    ports:
      - 5432:5432
    networks:
      - app-network 

  redis:
    image: redis:alpine
    container_name: fwd-redis
    restart: always
    command: ["redis-server" , "--bind" , "0.0.0.0" , "--port" , "6379"]
    ports:
      - 6379:6379
    networks:
      - app-network    
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    container_name: fwd-server
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge